substitutions:
  node_name: esp32cam-door
  device_name: Cam
  device_ip: 10.0.0.184

esphome:
  name: $node_name
  comment: $device_name
  platform: ESP32
  board: esp32dev

wifi:
  use_address: $device_ip
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  reboot_timeout: 0s
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret wifi_ap_password
    ap_timeout: 1min
    
captive_portal:
  
web_server:
  port: 80

logger:

debug:
  update_interval: 120s

api:
  reboot_timeout: 10s

ota:

switch:
  - platform: restart
    id: reboot
    name: $device_name Restart
    icon: mdi:restart

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]

  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  name: $device_name
  # idle_framerate: 1fps
  max_framerate: 3fps
  vertical_flip: True

esp32_camera_web_server:
  - port: 8080
    mode: stream

output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: led
light:
  - platform: monochromatic
    output: led
    name: $device_name light
