#//////////////////////////////////////////////////////////////////////////////
#Basic Settings
#//////////////////////////////////////////////////////////////////////////////
substitutions:
  node_name: sonoff-pow-r2-server
  device_name: Server PCM
  device_ip: 10.0.0.199

esphome:
  name: $node_name
  comment: $device_name

esp8266:
  board: esp8285

wifi:
  use_address: $device_ip
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret wifi_ap_password
    ap_timeout: 1min
    
captive_portal:
  
web_server:
  port: 80

logger:
  baud_rate: 0

debug:
  update_interval: 120s

uart:
  rx_pin: RX
  baud_rate: 4800

api:
  reboot_timeout: 0s
  encryption: 
    key: !secret encryption_key

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

#//////////////////////////////////////////////////////////////////////////////
#Switch Settings
#//////////////////////////////////////////////////////////////////////////////
binary_sensor:
  - platform: gpio
    name: $device_name Button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      - light.toggle: led_1
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: relay_1
    on_release:
      - light.toggle: led_1

  - platform: status
    name: $device_name Status

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO12
    name: $device_name Power Suply
    icon: mdi:server-network
    restore_mode: ALWAYS_ON

button:
  - platform: restart
    name: $device_name Restart

light:
  - platform: status_led
    id: led_1
    pin: GPIO13
    name: $device_name LED
    icon: mdi:led-variant-on

sensor:
  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 60s
    
  - platform: cse7766
    current:
      id: current
      name: $device_name Current
    voltage:
      id: voltage
      name: $device_name Voltage
    power:
      id: power
      name: $device_name Power
    energy:
      id: energy
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      name: $device_name Energy
    update_interval: 20s

  - platform: total_daily_energy
    id: daily_energy_usage
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    name: $device_name Total Daily Usage

  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"