#//////////////////////////////////////////////////////////////////////////////
#Basic Settings
#//////////////////////////////////////////////////////////////////////////////
substitutions:
  node_name: sonoff-touch-bathroom
  device_name: Bathroom
  device_ip: 10.0.0.196

esphome:
  name: $node_name
  comment: $device_name

esp8266:
  board: esp8285

wifi:
  use_address: $device_ip
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret wifi_ap_password
    ap_timeout: 1min
    
captive_portal:
  
web_server:
  port: 80

logger:

debug:
  update_interval: 120s

api:
  encryption: 
    key: !secret encryption_key

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

#//////////////////////////////////////////////////////////////////////////////
#Switch Settings
#//////////////////////////////////////////////////////////////////////////////
binary_sensor:
  - platform: gpio
    name: $device_name Button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      - light.toggle: led_1
      - light.toggle: light_1
    on_release:
      - light.toggle: led_1

  - platform: status
    name: $device_name Status

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12

button:
  - platform: restart
    name: $device_name Restart

light:
  - platform: status_led
    id: led_1
    pin: GPIO13
    name: $device_name LED
    icon: mdi:led-variant-on
    
  - platform: binary
    id: light_1
    output: relay_1
    name: $device_name Light
    icon: mdi:lightbulb-spot
    restore_mode: ALWAYS_OFF

sensor:
  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 60s

  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"